# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - datamodule: prototype.yaml
  - model: protonet.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml
  - trainer: default.yaml
  - log_dir: default.yaml

  # experiment configs allow for version control of specific configurations
  # e.g. best hyperparameters for each combination of model and datamodule
  - experiment: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

  # config for hyperparameter optimization
  - hparams_search: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
original_work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${original_work_dir}/data/

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# seed for random number generators in pytorch, numpy and python.random
seed: 1234

disable_cudnn: False

# default name for the experiment, determines logging folder path
# (you can overwrite this name in experiment configs)
name: "baseline"

exp_name: "test"

set:
  features: false
  train: true
  eval: false

path:
  # From the log directory
  root_dir: /import/c4dm-datasets/jinhua-tmp2May/DCASE_Task5
  train_dir: ${path.root_dir}/Development_Set/Training_Set
  eval_dir: ${path.root_dir}/Development_Set/Validation_Set
  # test_dir: ${path.root_dir}/Test_Set
  test_dir: null
  extra_train_dir: null
  mask_dir: null

features:
  eps: 2e-16
  fmax: 11025
  fmin: 50
  sr: 22050
  n_fft: 1024
  n_mels: 128
  hop_mel: 256
  # feature_types: rms@pcen@mel@mfcc@spectral_centroid@spectral_contrast@spectral_flatness@spectral_bandwidth@spectral_rolloff@poly_features@zero_crossing_rate@delta_mfcc
  feature_types: logmel
  embedding_dim: 2048
  drop_rate: 0.1
  with_bias: false
  non_linearity: leaky_relu
  time_max_pool_dim: 4
  layer_4: false
  test_seglen_len_lim: 30
  test_hoplen_fenmu: 3

train_param:
  exp_name: ${exp_name}
  sr: 22050
  seg_len: 0.2
  n_shot: 5
  k_way: 10
  device: cuda
  lr_rate: 0.001
  scheduler_gamma: 0.65
  scheduler_step_size: 10
  num_episodes: 2000
  adaptive_seg_len: true
  use_validation_first_5: false  # NOTE: DON'T ENABLE TRANSDUCTIVE LEARNING IN THE CHALLENGE
  negative_train_contrast: true
  load_weight_from: null
  negative_seg_search: false
  merging_segment: false
  remove_long_segment: false
  padd_tail: false

eval_param:
  seg_len: 0.200
  hop_seg: 0.05
  samples_neg: 150
  iterations: 3
  query_batch_size: 8
  negative_set_batch_size: 16
  threshold: 0.9
  negative_estimate: freq_mask